create database joins;
use joins;

CREATE TABLE cliente (
 CODCLI CHAR(3) NOT NULL PRIMARY KEY,
 NOME VARCHAR(40) NOT NULL,
 ENDERECO VARCHAR(50) NOT NULL,
 CIDADE VARCHAR(20) NOT NULL,
 ESTADO CHAR(2) NOT NULL,
 CEP CHAR(9) NOT NULL
);

CREATE TABLE venda (
 DUPLIC CHAR(6) NOT NULL PRIMARY KEY,
 VALOR DECIMAL(10,2) NOT NULL,
 VENCTO DATE NOT NULL,
 CODCLI CHAR(3) NOT NULL,
 FOREIGN KEY (CODCLI) REFERENCES cliente (CODCLI)
);

-- clientes
INSERT INTO cliente VALUES (
 '250',
 'BANCO BARCA S/A',
 'R. VITO, 34',
 'SAO SEBASTIAO',
 'CE',
 '62380-000'
);

INSERT INTO cliente VALUES (
 '820',
 'MECANICA SAO PAULO',
 'R. DO MACUCO, 99',
 'SANTO ANTONIO',
 'ES',
 '29810-020'
);

INSERT INTO cliente VALUES (
 '170',
 'POSTO BRASIL LTDA.',
 'AV. IMPERIO, 85',
 'GUAGIRUS',
 'BA',
 '42837-000'
);

-- vendas 
INSERT INTO venda VALUES (
 '230001',
 1300.00,
 '2001-06-10',
 '250'
);

INSERT INTO venda VALUES (
 '230099',
 1000.00,
 '2002-10-02',
 '820'
);

INSERT INTO venda VALUES (
 '997818',
 3000.00,
 '2001-11-11',
 '170'
);

-- consultas
-- NOME CLIENTE E DUPLIC

SELECT CLIENTE.NOME, VENDA.DUPLIC
FROM CLIENTE, VENDA 
WHERE CLIENTE.CODCLI = VENDA.CODCLI;

-- CONSULTA COM INNER JOIN
SELECT VENDA.DUPLIC, CLIENTE.NOME, CLIENTE.CIDADE
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
ORDER BY CLIENTE.NOME;

SELECT CLIENTE.NOME, COUNT(*) AS QTDE
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;

SELECT CLIENTE.NOME, sum(VENDA.VALOR) AS TOTAL
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;

SELECT CLIENTE.NOME, VENDA.DUPLIC, max(VENDA.VALOR) AS MAIOR_VENDA
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY VENDA.DUPLIC;

SELECT CLIENTE.NOME, VENDA.DUPLIC, min(VENDA.VALOR) AS MENOR_VENDA
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY VENDA.DUPLIC;

-- TABELA NOVA PARA USO DE INNER JOIN, LEFT E RIGHT
CREATE TABLE EX (
NOME VARCHAR(100)
);

CREATE TABLE FX (
NOME VARCHAR (100)
);

INSERT INTO EX VALUES ("BRUNO");
INSERT INTO EX VALUES ("BEATRIZ");
INSERT INTO EX VALUES ("LUIZA");
INSERT INTO EX VALUES ("VICTOR");
INSERT INTO EX VALUES ("VITORIA");

INSERT INTO FX VALUES ("BRUNO");
INSERT INTO FX VALUES ("MARIA");
INSERT INTO FX VALUES ("LUIZA");
INSERT INTO FX VALUES ("BRENDA");
INSERT INTO FX VALUES ("VIVIANE");

SELECT EX.NOME, FX.NOME
FROM EX INNER JOIN FX
ON EX.NOME = FX.NOME;

SELECT EX.NOME, FX.NOME
FROM EX AS EX
LEFT JOIN FX AS FX
  ON EX.NOME = FX.NOME;
  
--

SELECT EX.NOME, FX.NOME
FROM EX AS EX
LEFT JOIN FX AS FX
  ON EX.NOME = FX.NOME
  
UNION

SELECT EX.NOME, FX.NOME
FROM EX AS EX
RIGHT JOIN FX AS FX 
   ON EX.NOME = FX.NOME;

SELECT CLIENTE.NOME, VENDA.VENCTO
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE YEAR(VENDA.VENCTO) = 2001 AND MONTH(VENDA.VENCTO) = 11
ORDER BY VENDA.VENCTO;

-- ATIVIDADE 1
SELECT CLIENTE.NOME, VENDA.DUPLIC, VENDA.VALOR
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE CLIENTE.NOME LIKE "%PCTEC%";

-- ATIVIDADE 2
SELECT CLIENTE.NOME, VENDA.VENCTO
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE YEAR(VENDA.VENCTO) = 2004 AND MONTH(VENDA.VENCTO) = 11
ORDER BY VENDA.VENCTO;

-- ATIVIDADE 3
SELECT CLIENTE.NOME, VENDA.DUPLIC, VENDA.VENCTO
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE MONTH(VENDA.VENCTO) = 10;

-- ATIVIDADE 4
SELECT CLIENTE.NOME, COUNT(VENDA.DUPLIC) AS QUANTIDADE_TITULOS, SUM(VENDA.VALOR) AS TOTAL_DEVIDO
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;

-- ATIVIDADE 5
SELECT CLIENTE.NOME, COUNT(VENDA.DUPLIC) AS QUANTIDADE_TITULOS, SUM(VENDA.VALOR) AS TOTAL_A_PAGAR
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;

-- ATIVIDADE 6
SELECT CLIENTE.NOME AS CLIENTE, COUNT(VENDA.DUPLIC) AS VENCIDOS
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE VENDA.VENCTO < '2003-12-31'
GROUP BY CLIENTE.NOME;

-- ATIVIDADE 7
SELECT CLIENTE.NOME, VENDA.VALOR, (VENDA.VALOR * 0.10) AS JUROS_10_PORCENTO, (VENDA.VALOR + (VENDA.VALOR * 0.10)) AS TOTAL_A_COBRAR
FROM CLIENTE INNER JOIN VENDA 
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE VENDA.VENCTO < '1999-12-31'
ORDER BY CLIENTE.NOME;

